version: '3.8'
services:
  super-frete-api:
    container_name: super-frete-api
    build:
      context: './'
      dockerfile: ./docker/api.dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/api
    env_file: .env
    restart: always